#!/bin/bash

command=$1
switchNo=$2
value1=$3
value2=$4

fileName=/srv/data/timeRange'.'$switchNo

case $command in
  set)  if [[ $value1 == [0-2][0-9]:[0-5][0-9] ]] && [[ $value2 == [0-2][0-9]:[0-5][0-9] ]]; then
		echo -e "$value1 \n$value2" > /srv/data/timeRange'.'$switchNo #$filename
	else
		if [[ -f $fileName ]]; then
			rm $fileName
		fi
	fi
  ;;
  showTRON) if [[ ! -f $fileName ]]; then
		  echo -e "<font color='red'>Not set</font>"
	    else
                  echo -e "<font color='green'>$(cat $fileName | head -n 1)</font>"
            fi
  ;;
  showTROFF) if [[ ! -f $fileName ]]; then
                  echo -e "<font color='red'>Not set</font>"
             else 
                  echo -e "<font color='green'>$(cat $fileName | tail -n 1)</font>"
             fi
  ;;
esac
