#!/bin/bash

command=$1

if [[ ! $command ]]; then
myStatus=$(/usr/bin/sudo /etc/init.d/mysql status|egrep running)

#echo $myStatus >> /var/www/html/ownpan/logs_/log.txt
  if [[ $myStatus ]]; then
    echo -e "<pre><font color="green">$myStatus</font></pre>"
  else
    echo -e "<pre><font color="red">MySQL is stopped..</font></pre>"
  fi
  exit
fi
#echo "$(date)MANAGE MySQL Issued $command" >> /var/www/html/ownpan/logs_/log.txt
case $command in
  stop) /usr/bin/sudo /etc/init.d/mysql stop
  ;;
  start) /usr/bin/sudo /etc/init.d/mysql start
  ;;
esac


